version: "3.8"

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

  fastapi:
    build: ./src
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: >
      sh -c '
        if [ "$DEBUG" = "1" ]; then
          echo "Running in debug mode..."
          uv run python -m debugpy --listen 0.0.0.0:5678 \
            -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload;
        else
          echo "Running normally..."
          uv run uvicorn main:app --host 0.0.0.0 --port 8001 --reload;
        fi
      '


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
