sonar.projectKey=gabriela-schuster_self-healing-gate
sonar.projectName=self-healing-gate

sonar.sources=src
sonar.inclusions=src/**/*.py

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.organization=gabriela-schuster