services:
  fastapi:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: >
      sh -c '
        if [ "$DEBUG" = "1" ]; then
          echo "Running in debug mode..."
          uv run python -m debugpy --listen 0.0.0.0:5678 \
            -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload;
        else
          echo "Running normally..."
          uv run uvicorn main:app --host 0.0.0.0 --port 8001 --reload;
        fi
      '

volumes:
  postgres_data:
  minio_data:

