jobs:
  sonar:
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name == 'main' && 'Dev' || 'Dev' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
